# Generated by Django 4.1 on 2022-08-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222)),
                ('position', models.CharField(max_length=222)),
                ('avatar', models.ImageField(upload_to='about/')),
                ('context', models.TextField()),
            ],
        ),
    ]
